#pragma kernel CSMain

struct Voxel
{
    int id;
};

int ChunkSize;
StructuredBuffer<Voxel> VoxelBuffer;
RWTexture2D<float4> ResultTexture;

[numthreads(8,8,1)]
void CSMain (uint3 i : SV_DispatchThreadID)
{
    int id = VoxelBuffer[i.y * ChunkSize + i.x].id;
    
    if (id == 0)
    {
        ResultTexture[i.xy] = float4(0, 0, 0, 0);
    }
    else
    {
        ResultTexture[i.xy] = float4(1, 1, 1, 1);
    }
}
