#pragma kernel TextureGen

struct Voxel
{
    int id;
};

int ChunkSize;
StructuredBuffer<Voxel> PixelBuffer;
RWTexture2D<float4> ResultTexture;

[numthreads(8,8,1)]
void TextureGen (uint3 i : SV_DispatchThreadID)
{
    int id = PixelBuffer[i.x * ChunkSize + i.y].id;
    
    if (id == 0)
    {
        ResultTexture[i.xy] = float4(0, 0, 0, 0);
    }
    else
    {
        ResultTexture[i.xy] = float4(.31, .2, .14, 1);
    }
}
